### ISSUE TITLE
Path not found for word file

### ISSUE THREAD

**Issue by metaember** [metaember/games#8]
When launching the game from the root directory, the word file is not found.

```
Traceback (most recent call last):
  File "hangman/hangman.py", line 54, in <module>
    WORDS = load_words()
  File "hangman/hangman.py", line 7, in load_words
    with open(file_name, 'r') as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'word_dictionary.txt'

```

**Comment by metaember** [comment]
Thanks @masatoshichang for the bugfix. This is closed by #9.
